### ISSUE TITLE
Error opening project

### ISSUE THREAD

**Issue by ghost** [DNoel26/My_Dev_Portfolio#1]
is there any dependency that must be installed or some path to be indicated in the file?
When I run the file in VsCode it goes completely wrong

**Comment by DNoel26** [comment]
Hi. No dependencies required. What exactly happens when you run the code?

**Comment by ghost** [comment]
Hi. It loads only HTML. It does not load images, styles, animations, shadows or anything else. Loads only the unconfigured HTML text.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66707031/110713832-56463b00-81e1-11eb-8a2b-bc5569d692e7.png)
![image](https://user-images.githubusercontent.com/66707031/110713873-6bbb6500-81e1-11eb-8d9f-25f7f4fc89f5.png)
![image](https://user-images.githubusercontent.com/66707031/110713904-75dd6380-81e1-11eb-926a-b5bf5f6b6fb4.png)
![image](https://user-images.githubusercontent.com/66707031/110713928-7d9d0800-81e1-11eb-8c3f-8780d8e4f262.png)
![image](https://user-images.githubusercontent.com/66707031/110713958-868dd980-81e1-11eb-9d02-f7c5ed39d7e4.png)

**Comment by ghost** [comment]
Forgive my incorrect writing.
I am Brazilian and I am using the translator to write English.
The truth is, of all the website projects I've found here on GitHub, yours is the most beautiful one I've ever seen.
I visited the site and found it fantastic!
Your project is incredible and I am very excited to see this fully functional code

**Comment by DNoel26** [comment]
Thanks for your kind words 😄 

I forgot, you need to ensure that Bootstrap is loaded, and all css/js/media/img files are loaded and included as well. Can I see your code? 

Seems like you've just pulled the html only.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66707031/110831287-d5d31900-8278-11eb-802a-8787d9f29f39.png)
Do not expand the image folders to avoid leaving the capture area, but they are all there.
See that in HTML there is already an annotation for Bootstrap via CDN

**Comment by DNoel26** [comment]
Hmm I'm not sure...I'll get back to you.

Did you have any luck though?

**Comment by ghost** [comment]
Hi! I installed Bootstrap via NPM and made notes. Unfortunately, it still didn't work. I really can't understand what's going on.
I hope that I am missing something simple, yet I am still standing in the same place with your project.

**Comment by DNoel26** [comment]
Hi, I found the issue. It's due to how I set my files' paths. I can change them and commit or what you can do is add the folder that you pulled to your IDE workspace and run it in live server until then.

**Comment by DNoel26** [comment]
Also, I use modules in this project, so Javascript will not work without running on live server. Let me know if it helps.

**Comment by ghost** [comment]
I downloaded it again after the update you did today. With a few bugs it is working very well. I believe that now I can fully study this beautiful project of yours.

**Comment by ghost** [comment]
I ran the project you loaded today using Xampp again. It worked perfectly and in its fullness. I am really grateful for all the help and support. Once again I reiterate that this is the most beautiful website project I have ever been able to find on GitHub.
Congratulations on this excellent work. I am fully convinced that your future in programming will be fantastic.
Thank you very much!

**Comment by DNoel26** [comment]
Great, glad you were able to get it running. Appreciate the positive feedback!
